version: "3.6"

services:
    nginx:
        image: nginx:1.21.3
        ports:
          - "8080:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./frontend/build:/app